import type { Metadata } from "next";
import { Source_Code_Pro } from "next/font/google";
import "./globals.css";
import Title from "./components/title";
import { config } from '@fortawesome/fontawesome-svg-core'
import '@fortawesome/fontawesome-svg-core/styles.css'
config.autoAddCss = false

const Code = Source_Code_Pro({ subsets: ["latin"] });


export const metadata: Metadata = {
  title: "One piece",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${Code.className} bg-slate-400`}>
        <Title />
        {children}</body>
    </html>
  );
}
